FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV MLFLOW_TRACKING_URI=sqlite:////app/mlflow/mlflow.db

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -i https://pypi.org/simple -r requirements.txt

COPY . .

RUN mkdir -p /app/mlflow && \
    mkdir -p /app/mlruns
EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]