
apiVersion: v1
kind: ConfigMap

metadata:
  name: voyage-config
  namespace: voyage-analytics

data:
  API_URL: "http://voyage-api-service:8000"
  MLFLOW_TRACKING_URI: "sqlite:////app/mlflow/mlflow.db"