apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: voyage-ingress
  namespace: voyage-analytics

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

spec:
  ingressClassName: nginx

  rules:
  - host: voyage.local

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: voyage-app-service

            port:
              number: 8501